#ifndef LOGICAL_COMMAND_INTERPRETER_COMMAND_HH
#define LOGICAL_COMMAND_INTERPRETER_COMMAND_HH

enum Command {
    DEFINE,
    SOLVE,
    FIND,
    ALL,
    QUIT
};

#endif //LOGICAL_COMMAND_INTERPRETER_COMMAND_HH
