#ifndef LOGICAL_EXPRESSION_INTERPRETER_OPERATOR_HH
#define LOGICAL_EXPRESSION_INTERPRETER_OPERATOR_HH

enum Operator {
    AND,
    OR,
    NOT
};

#endif //LOGICAL_EXPRESSION_INTERPRETER_OPERATOR_HH
